package com.qingwenwei.persistence.model;

import java.util.Date;

public class RApplyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_apply.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_apply.jobid
     *
     * @mbggenerated
     */
    private Integer jobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_apply.apply_date
     *
     * @mbggenerated
     */
    private Date applyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_apply.userid
     *
     * @return the value of r_apply.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_apply.userid
     *
     * @param userid the value for r_apply.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_apply.jobid
     *
     * @return the value of r_apply.jobid
     *
     * @mbggenerated
     */
    public Integer getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_apply.jobid
     *
     * @param jobid the value for r_apply.jobid
     *
     * @mbggenerated
     */
    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_apply.apply_date
     *
     * @return the value of r_apply.apply_date
     *
     * @mbggenerated
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_apply.apply_date
     *
     * @param applyDate the value for r_apply.apply_date
     *
     * @mbggenerated
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }
}