package com.qingwenwei.persistence.model;

public class RApply extends RApplyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_apply.apply_status
     *
     * @mbggenerated
     */
    private String applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_apply.compId
     *
     * @mbggenerated
     */
    private Integer compid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_apply.apply_status
     *
     * @return the value of r_apply.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_apply.apply_status
     *
     * @param applyStatus the value for r_apply.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_apply.compId
     *
     * @return the value of r_apply.compId
     *
     * @mbggenerated
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_apply.compId
     *
     * @param compid the value for r_apply.compId
     *
     * @mbggenerated
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }
}