package com.qingwenwei.persistence.model;

import java.math.BigDecimal;
import java.util.Date;

public class RCompanycharge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_companycharge.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_companycharge.chargedate
     *
     * @mbggenerated
     */
    private Date chargedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_companycharge.chargeid
     *
     * @mbggenerated
     */
    private Integer chargeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_companycharge.chargetime
     *
     * @mbggenerated
     */
    private Date chargetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_companycharge.chargeamt
     *
     * @mbggenerated
     */
    private BigDecimal chargeamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_companycharge.id
     *
     * @return the value of r_companycharge.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_companycharge.id
     *
     * @param id the value for r_companycharge.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_companycharge.chargedate
     *
     * @return the value of r_companycharge.chargedate
     *
     * @mbggenerated
     */
    public Date getChargedate() {
        return chargedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_companycharge.chargedate
     *
     * @param chargedate the value for r_companycharge.chargedate
     *
     * @mbggenerated
     */
    public void setChargedate(Date chargedate) {
        this.chargedate = chargedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_companycharge.chargeid
     *
     * @return the value of r_companycharge.chargeid
     *
     * @mbggenerated
     */
    public Integer getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_companycharge.chargeid
     *
     * @param chargeid the value for r_companycharge.chargeid
     *
     * @mbggenerated
     */
    public void setChargeid(Integer chargeid) {
        this.chargeid = chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_companycharge.chargetime
     *
     * @return the value of r_companycharge.chargetime
     *
     * @mbggenerated
     */
    public Date getChargetime() {
        return chargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_companycharge.chargetime
     *
     * @param chargetime the value for r_companycharge.chargetime
     *
     * @mbggenerated
     */
    public void setChargetime(Date chargetime) {
        this.chargetime = chargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_companycharge.chargeamt
     *
     * @return the value of r_companycharge.chargeamt
     *
     * @mbggenerated
     */
    public BigDecimal getChargeamt() {
        return chargeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_companycharge.chargeamt
     *
     * @param chargeamt the value for r_companycharge.chargeamt
     *
     * @mbggenerated
     */
    public void setChargeamt(BigDecimal chargeamt) {
        this.chargeamt = chargeamt;
    }
}