package com.qingwenwei.persistence.model;

public class RCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.crdt_code
     *
     * @mbggenerated
     */
    private String crdtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.legal_name
     *
     * @mbggenerated
     */
    private String legalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.field
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.regicapital
     *
     * @mbggenerated
     */
    private Integer regicapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_company.busi_type_comp
     *
     * @mbggenerated
     */
    private String busiTypeComp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.id
     *
     * @return the value of r_company.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.id
     *
     * @param id the value for r_company.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.nickname
     *
     * @return the value of r_company.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.nickname
     *
     * @param nickname the value for r_company.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.name
     *
     * @return the value of r_company.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.name
     *
     * @param name the value for r_company.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.crdt_code
     *
     * @return the value of r_company.crdt_code
     *
     * @mbggenerated
     */
    public String getCrdtCode() {
        return crdtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.crdt_code
     *
     * @param crdtCode the value for r_company.crdt_code
     *
     * @mbggenerated
     */
    public void setCrdtCode(String crdtCode) {
        this.crdtCode = crdtCode == null ? null : crdtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.legal_name
     *
     * @return the value of r_company.legal_name
     *
     * @mbggenerated
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.legal_name
     *
     * @param legalName the value for r_company.legal_name
     *
     * @mbggenerated
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName == null ? null : legalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.mobile
     *
     * @return the value of r_company.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.mobile
     *
     * @param mobile the value for r_company.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.phone_num
     *
     * @return the value of r_company.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.phone_num
     *
     * @param phoneNum the value for r_company.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.address
     *
     * @return the value of r_company.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.address
     *
     * @param address the value for r_company.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.email
     *
     * @return the value of r_company.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.email
     *
     * @param email the value for r_company.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.field
     *
     * @return the value of r_company.field
     *
     * @mbggenerated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.field
     *
     * @param field the value for r_company.field
     *
     * @mbggenerated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.size
     *
     * @return the value of r_company.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.size
     *
     * @param size the value for r_company.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.regicapital
     *
     * @return the value of r_company.regicapital
     *
     * @mbggenerated
     */
    public Integer getRegicapital() {
        return regicapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.regicapital
     *
     * @param regicapital the value for r_company.regicapital
     *
     * @mbggenerated
     */
    public void setRegicapital(Integer regicapital) {
        this.regicapital = regicapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.type
     *
     * @return the value of r_company.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.type
     *
     * @param type the value for r_company.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_company.busi_type_comp
     *
     * @return the value of r_company.busi_type_comp
     *
     * @mbggenerated
     */
    public String getBusiTypeComp() {
        return busiTypeComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_company.busi_type_comp
     *
     * @param busiTypeComp the value for r_company.busi_type_comp
     *
     * @mbggenerated
     */
    public void setBusiTypeComp(String busiTypeComp) {
        this.busiTypeComp = busiTypeComp == null ? null : busiTypeComp.trim();
    }
}