package com.qingwenwei.persistence.model;

import java.util.Date;

public class RJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.comp
     *
     * @mbggenerated
     */
    private Integer comp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.post_date
     *
     * @mbggenerated
     */
    private Date postDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.expiry_date
     *
     * @mbggenerated
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.jobtype
     *
     * @mbggenerated
     */
    private String jobtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.jobabstract
     *
     * @mbggenerated
     */
    private String jobabstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.jobcontent
     *
     * @mbggenerated
     */
    private String jobcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_job.busi_type_job
     *
     * @mbggenerated
     */
    private String busiTypeJob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.id
     *
     * @return the value of r_job.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.id
     *
     * @param id the value for r_job.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.comp
     *
     * @return the value of r_job.comp
     *
     * @mbggenerated
     */
    public Integer getComp() {
        return comp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.comp
     *
     * @param comp the value for r_job.comp
     *
     * @mbggenerated
     */
    public void setComp(Integer comp) {
        this.comp = comp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.post_date
     *
     * @return the value of r_job.post_date
     *
     * @mbggenerated
     */
    public Date getPostDate() {
        return postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.post_date
     *
     * @param postDate the value for r_job.post_date
     *
     * @mbggenerated
     */
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.expiry_date
     *
     * @return the value of r_job.expiry_date
     *
     * @mbggenerated
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.expiry_date
     *
     * @param expiryDate the value for r_job.expiry_date
     *
     * @mbggenerated
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.title
     *
     * @return the value of r_job.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.title
     *
     * @param title the value for r_job.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.location
     *
     * @return the value of r_job.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.location
     *
     * @param location the value for r_job.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.jobtype
     *
     * @return the value of r_job.jobtype
     *
     * @mbggenerated
     */
    public String getJobtype() {
        return jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.jobtype
     *
     * @param jobtype the value for r_job.jobtype
     *
     * @mbggenerated
     */
    public void setJobtype(String jobtype) {
        this.jobtype = jobtype == null ? null : jobtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.jobabstract
     *
     * @return the value of r_job.jobabstract
     *
     * @mbggenerated
     */
    public String getJobabstract() {
        return jobabstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.jobabstract
     *
     * @param jobabstract the value for r_job.jobabstract
     *
     * @mbggenerated
     */
    public void setJobabstract(String jobabstract) {
        this.jobabstract = jobabstract == null ? null : jobabstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.jobcontent
     *
     * @return the value of r_job.jobcontent
     *
     * @mbggenerated
     */
    public String getJobcontent() {
        return jobcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.jobcontent
     *
     * @param jobcontent the value for r_job.jobcontent
     *
     * @mbggenerated
     */
    public void setJobcontent(String jobcontent) {
        this.jobcontent = jobcontent == null ? null : jobcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.phone_num
     *
     * @return the value of r_job.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.phone_num
     *
     * @param phoneNum the value for r_job.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.email
     *
     * @return the value of r_job.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.email
     *
     * @param email the value for r_job.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_job.busi_type_job
     *
     * @return the value of r_job.busi_type_job
     *
     * @mbggenerated
     */
    public String getBusiTypeJob() {
        return busiTypeJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_job.busi_type_job
     *
     * @param busiTypeJob the value for r_job.busi_type_job
     *
     * @mbggenerated
     */
    public void setBusiTypeJob(String busiTypeJob) {
        this.busiTypeJob = busiTypeJob == null ? null : busiTypeJob.trim();
    }
}