package com.qingwenwei.persistence.model;

public class RParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_param.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_param.param_name
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_param.param_value
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_param.id
     *
     * @return the value of r_param.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_param.id
     *
     * @param id the value for r_param.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_param.param_name
     *
     * @return the value of r_param.param_name
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_param.param_name
     *
     * @param paramName the value for r_param.param_name
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_param.param_value
     *
     * @return the value of r_param.param_value
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_param.param_value
     *
     * @param paramValue the value for r_param.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }
}