package com.qingwenwei.persistence.model;

import java.util.Date;

public class RPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.postdate
     *
     * @mbggenerated
     */
    private Date postdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.posttime
     *
     * @mbggenerated
     */
    private Date posttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.editdate
     *
     * @mbggenerated
     */
    private Date editdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.edittime
     *
     * @mbggenerated
     */
    private Date edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.reviewer
     *
     * @mbggenerated
     */
    private String reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.postsource
     *
     * @mbggenerated
     */
    private String postsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.clickcount
     *
     * @mbggenerated
     */
    private Integer clickcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.collectcount
     *
     * @mbggenerated
     */
    private Integer collectcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_post.postcontent
     *
     * @mbggenerated
     */
    private byte[] postcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.id
     *
     * @return the value of r_post.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.id
     *
     * @param id the value for r_post.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.category
     *
     * @return the value of r_post.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.category
     *
     * @param category the value for r_post.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.title
     *
     * @return the value of r_post.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.title
     *
     * @param title the value for r_post.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.subtitle
     *
     * @return the value of r_post.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.subtitle
     *
     * @param subtitle the value for r_post.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.postdate
     *
     * @return the value of r_post.postdate
     *
     * @mbggenerated
     */
    public Date getPostdate() {
        return postdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.postdate
     *
     * @param postdate the value for r_post.postdate
     *
     * @mbggenerated
     */
    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.posttime
     *
     * @return the value of r_post.posttime
     *
     * @mbggenerated
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.posttime
     *
     * @param posttime the value for r_post.posttime
     *
     * @mbggenerated
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.editdate
     *
     * @return the value of r_post.editdate
     *
     * @mbggenerated
     */
    public Date getEditdate() {
        return editdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.editdate
     *
     * @param editdate the value for r_post.editdate
     *
     * @mbggenerated
     */
    public void setEditdate(Date editdate) {
        this.editdate = editdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.edittime
     *
     * @return the value of r_post.edittime
     *
     * @mbggenerated
     */
    public Date getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.edittime
     *
     * @param edittime the value for r_post.edittime
     *
     * @mbggenerated
     */
    public void setEdittime(Date edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.author
     *
     * @return the value of r_post.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.author
     *
     * @param author the value for r_post.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.reviewer
     *
     * @return the value of r_post.reviewer
     *
     * @mbggenerated
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.reviewer
     *
     * @param reviewer the value for r_post.reviewer
     *
     * @mbggenerated
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.postsource
     *
     * @return the value of r_post.postsource
     *
     * @mbggenerated
     */
    public String getPostsource() {
        return postsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.postsource
     *
     * @param postsource the value for r_post.postsource
     *
     * @mbggenerated
     */
    public void setPostsource(String postsource) {
        this.postsource = postsource == null ? null : postsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.clickcount
     *
     * @return the value of r_post.clickcount
     *
     * @mbggenerated
     */
    public Integer getClickcount() {
        return clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.clickcount
     *
     * @param clickcount the value for r_post.clickcount
     *
     * @mbggenerated
     */
    public void setClickcount(Integer clickcount) {
        this.clickcount = clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.collectcount
     *
     * @return the value of r_post.collectcount
     *
     * @mbggenerated
     */
    public Integer getCollectcount() {
        return collectcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.collectcount
     *
     * @param collectcount the value for r_post.collectcount
     *
     * @mbggenerated
     */
    public void setCollectcount(Integer collectcount) {
        this.collectcount = collectcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.comments
     *
     * @return the value of r_post.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.comments
     *
     * @param comments the value for r_post.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_post.postcontent
     *
     * @return the value of r_post.postcontent
     *
     * @mbggenerated
     */
    public byte[] getPostcontent() {
        return postcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_post.postcontent
     *
     * @param postcontent the value for r_post.postcontent
     *
     * @mbggenerated
     */
    public void setPostcontent(byte[] postcontent) {
        this.postcontent = postcontent;
    }
}