package com.qingwenwei.persistence.model;

import java.util.Date;

public class RToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_token.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_token.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_token.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_token.expirydate
     *
     * @mbggenerated
     */
    private Date expirydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_token.id
     *
     * @return the value of r_token.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_token.id
     *
     * @param id the value for r_token.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_token.token
     *
     * @return the value of r_token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_token.token
     *
     * @param token the value for r_token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_token.userid
     *
     * @return the value of r_token.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_token.userid
     *
     * @param userid the value for r_token.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_token.expirydate
     *
     * @return the value of r_token.expirydate
     *
     * @mbggenerated
     */
    public Date getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_token.expirydate
     *
     * @param expirydate the value for r_token.expirydate
     *
     * @mbggenerated
     */
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }
}