package com.qingwenwei.persistence.model;

public class RUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.crdt_type
     *
     * @mbggenerated
     */
    private String crdtType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.crdt_num
     *
     * @mbggenerated
     */
    private String crdtNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.busi_type_user
     *
     * @mbggenerated
     */
    private String busiTypeUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.remark1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.remark2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user.remark3
     *
     * @mbggenerated
     */
    private String remark3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.id
     *
     * @return the value of r_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.id
     *
     * @param id the value for r_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.nickname
     *
     * @return the value of r_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.nickname
     *
     * @param nickname the value for r_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.name
     *
     * @return the value of r_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.name
     *
     * @param name the value for r_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.crdt_type
     *
     * @return the value of r_user.crdt_type
     *
     * @mbggenerated
     */
    public String getCrdtType() {
        return crdtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.crdt_type
     *
     * @param crdtType the value for r_user.crdt_type
     *
     * @mbggenerated
     */
    public void setCrdtType(String crdtType) {
        this.crdtType = crdtType == null ? null : crdtType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.crdt_num
     *
     * @return the value of r_user.crdt_num
     *
     * @mbggenerated
     */
    public String getCrdtNum() {
        return crdtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.crdt_num
     *
     * @param crdtNum the value for r_user.crdt_num
     *
     * @mbggenerated
     */
    public void setCrdtNum(String crdtNum) {
        this.crdtNum = crdtNum == null ? null : crdtNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.phone_num
     *
     * @return the value of r_user.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.phone_num
     *
     * @param phoneNum the value for r_user.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.address
     *
     * @return the value of r_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.address
     *
     * @param address the value for r_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.email
     *
     * @return the value of r_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.email
     *
     * @param email the value for r_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.busi_type_user
     *
     * @return the value of r_user.busi_type_user
     *
     * @mbggenerated
     */
    public String getBusiTypeUser() {
        return busiTypeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.busi_type_user
     *
     * @param busiTypeUser the value for r_user.busi_type_user
     *
     * @mbggenerated
     */
    public void setBusiTypeUser(String busiTypeUser) {
        this.busiTypeUser = busiTypeUser == null ? null : busiTypeUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.remark1
     *
     * @return the value of r_user.remark1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.remark1
     *
     * @param remark1 the value for r_user.remark1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.remark2
     *
     * @return the value of r_user.remark2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.remark2
     *
     * @param remark2 the value for r_user.remark2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user.remark3
     *
     * @return the value of r_user.remark3
     *
     * @mbggenerated
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user.remark3
     *
     * @param remark3 the value for r_user.remark3
     *
     * @mbggenerated
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }
}