package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RComment;
import com.qingwenwei.persistence.model.RCommentExample;
import java.util.List;

public interface RCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    int insert(RComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    int insertSelective(RComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    List<RComment> selectByExample(RCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    RComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RComment record);
}