package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RCompany;
import com.qingwenwei.persistence.model.RCompanyExample;
import java.util.List;

public interface RCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    int insert(RCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    int insertSelective(RCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    List<RCompany> selectByExample(RCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    RCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RCompany record);
}