package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RCompanycharge;
import com.qingwenwei.persistence.model.RCompanychargeExample;
import java.util.List;

public interface RCompanychargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    int insert(RCompanycharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    int insertSelective(RCompanycharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    List<RCompanycharge> selectByExample(RCompanychargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    RCompanycharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RCompanycharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_companycharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RCompanycharge record);
}