package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RParam;
import com.qingwenwei.persistence.model.RParamExample;
import java.util.List;

public interface RParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    int insert(RParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    int insertSelective(RParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    List<RParam> selectByExample(RParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    RParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RParam record);
}