package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RPost;
import com.qingwenwei.persistence.model.RPostExample;
import java.util.List;

public interface RPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    int insert(RPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    int insertSelective(RPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    List<RPost> selectByExampleWithBLOBs(RPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    List<RPost> selectByExample(RPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    RPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RPost record);
}