package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RToken;
import com.qingwenwei.persistence.model.RTokenExample;
import java.util.List;

public interface RTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    int insert(RToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    int insertSelective(RToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    List<RToken> selectByExample(RTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    RToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RToken record);
}