package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RUser;
import com.qingwenwei.persistence.model.RUserExample;
import java.util.List;

public interface RUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    int insert(RUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    int insertSelective(RUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    List<RUser> selectByExample(RUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    RUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RUser record);
}