package com.qingwenwei.persistence.dao;

import com.qingwenwei.persistence.model.RUsercharge;
import com.qingwenwei.persistence.model.RUserchargeExample;
import java.util.List;

public interface RUserchargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    int insert(RUsercharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    int insertSelective(RUsercharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    List<RUsercharge> selectByExample(RUserchargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    RUsercharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RUsercharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_usercharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RUsercharge record);
}